- name: SSH into EC2 and run deployment script
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    script: |
      cd ~/test-app
      git pull origin main
      chmod +x gradlew
      ./gradlew assembleRelease

      # Set AWS env vars
      export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

      # Upload APK
      aws s3 cp app/build/outputs/apk/release/app-release.apk s3://${{ secrets.S3_BUCKET }}/builds/
      echo "Deployment completed and APK uploaded to S3"
